### ISSUE TITLE
Não vale a pena colocar o comando que pede autorização para o papi no Makefile em vez do run.sh?

### ISSUE THREAD

**Issue by Sergiorezende22** [yaansz/architecture-2#2]
Esses duas linhas de comandos não deveriam estar no makefile?
```bash
echo "[WARNING] papi needs to get permission to read system events"
sudo sh -c 'echo 0 >/proc/sys/kernel/perf_event_paranoid'
```

**Comment by yaansz** [comment]
N necessariamente,  ele sempre roda isso quando o pc inicia né? Então acho que n

**Comment by Sergiorezende22** [comment]
Sim, mas toda vez que der run vai rodar isso, acho que agnt usa mais o run do que o make e esse código so precisa rodar uma vez.

**Comment by yaansz** [comment]
Essa responsabilidade ser do makefile não parece certo, nem sempre vamos compilar o programa
